name: pooled-cell-painting
channels:
- conda-forge
dependencies:
- conda-forge::python=3.7.1
- conda-forge::pandas=1.2
- conda-forge::numpy=1.20
- conda-forge::pathlib=1.0.1
- conda-forge::jupyter=1.0.0
- conda-forge::jupyterlab=3.0.15
- conda-forge::ipykernel=5.1.0
- conda-forge::nb_conda_kernels=2.2.1
- conda-forge::widgetsnbextension=3.5.1
- conda-forge::jupyter_contrib_nbextensions=0.5.1
- conda-forge::matplotlib=3.1.3
- conda-forge::plotnine=0.8.0
- conda-forge::seaborn=0.10.1
- conda-forge::black=19.10b0
- conda-forge::nb_black=1.0.7
- pip:
  - git+https://github.com/cytomining/pycytominer@fdd0e0935ab5446f5c3710e5270c5234d8ef18f1
  - git+https://github.com/cytomining/cytominer-eval@7f94b1124c9043c5e3717c43eb317a389e4b8efa
