---
core:
  compartments:
    - Cells
    - Nuclei
    - Cytoplasm
  cell_quality:
    categorize_cell_quality: simple
    cell_filter:
      - Perfect
      - Great
    cell_quality_column: Metadata_Foci_Cell_Quality
    cell_quality_index: Metadata_Foci_Cell_Quality_Index
  cell_id_cols:
    - ImageNumber
    - ObjectNumber
  cell_match_cols:
    cells:
      - Parent_Nuclei
    cytoplasm:
      - Parent_Nuclei
      - Parent_Cells
    spots:
      - Parent_Cells
  compression: gzip
  float_format: "%.5g"
  ignore_files:
    - .DS_Store
---
preprocess:
  prefilter:
    perform: true
    force_overwrite: true
    flag_cols:
      - Barcode
      - Location
      - Count
      - Resize
  process-spots:
    perform: true
    force_overwrite: true
    allowed_skips: 10
    image_cols:
      full_info: "Metadata_site"
      well: "Metadata_Well"
      site: "Metadata_Site"
      plate: "Metadata_Plate"
    barcode_cols:
      - Barcode_MatchedTo_Barcode
    gene_cols:
      - Barcode_MatchedTo_GeneCode
    location_cols:
      - Location_Center_X
      - Location_Center_Y
    spot_score_cols:
      - Barcode_MatchedTo_Score
    foci_cols:
      - Barcode_BarcodeCalled
      - Barcode_MatchedTo_ID
    exact_match_reads_col: "exact_match_reads_per_cell"
    drop_barcodes:
      - AAAATTTTCCCCGGGG
  process-cells:
    perform: true
    force_overwrite: true
    sort_col: Metadata_Cells_ObjectNumber
    merge_columns:
      image_column: ImageNumber
      linking_compartment: Cytoplasm
      linking_columns:
        cells: Metadata_Cytoplasm_Parent_Cells
        nuclei: Metadata_Cytoplasm_Parent_Nuclei
    metadata_merge_columns:
      foci_cols:
        - Metadata_Foci_ImageNumber
        - Metadata_Foci_Parent_Cells
      cell_cols:
        - Metadata_Cells_ImageNumber
        - Metadata_Cells_ObjectNumber
    foci_site_col: Metadata_Foci_site
  summarize-cells:
    perform: true
    force_overwrite: true
  summarize-plate:
    perform: true
    force_overwrite: true
    correlation_threshold: .2
    painting_image_names:
      - ConA
      - Hoechst
      - Mito
      - SYTO
      - WGA
    barcoding_prefix: CorrCycle
---
profile:
  single_cell:
    perform: true
    force_overwrite: true
    prefilter_features: true
    output_one_single_cell_file_only: true
    allowed_skips: 10
    cell_quality_column: Metadata_Foci_Cell_Quality
    sanitize_gene_col: true
    merge_columns:
      image_column: ImageNumber
      linking_compartment: Cytoplasm
      linking_columns:
        cells: Metadata_Cytoplasm_Parent_Cells
        nuclei: Metadata_Cytoplasm_Parent_Nuclei
      metadata_linking_columns:
        - Metadata_Foci_site
        - Metadata_Cells_ObjectNumber
  aggregate:
    perform: true
    force_overwrite: true
    operation: median
    features: infer
    levels:
      gene:
        - Metadata_Foci_Barcode_MatchedTo_GeneCode
      guide:
        - Metadata_Foci_Barcode_MatchedTo_GeneCode
        - Metadata_Foci_Barcode_MatchedTo_Barcode
  normalize:
    perform: true
    force_overwrite: true
    output_single_cell_by_guide: true
    method: standardize
    levels:
      - gene
      - guide
      - single_cell
    by_samples: all
    features: infer
  feature_select:
    perform: true
    force_overwrite: true
    operations:
      - variance_threshold
      - correlation_threshold
      - drop_na_columns
      - blocklist
      - drop_outliers
    levels:
      - gene
      - guide
      - single_cell
    use_samples: all
    features: infer
    na_cutoff: 0
    corr_threshold: 0.9
